volumes:
  nifi_registry_database:
  nifi_registry_flow_storage:
  nifi_database_repository:
  nifi_flowfile_repository:
  nifi_content_repository:
  nifi_provenance_repository:
  nifi_nar_extensions:
  nifi_python_extensions:
  nifi_conf:
  nifi_state:
  nifi_logs:

networks:
  nifi_network:
    driver: bridge

services:

  nifi-registry:
    image: apache/nifi-registry:2.6.0
    container_name: nifi-registry-staging
    hostname: nifi-registry
    user: root
    ports:
      - "${NIFI_REGISTRY_PORT}:18080"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=${NIFI_REGISTRY_PORT}
      - NIFI_REGISTRY_WEB_HTTP_HOST=${NIFI_REGISTRY_HOST}
      - ENVIRONMENT=staging
    mem_limit: 1g
    restart: unless-stopped
    volumes:
      - nifi_registry_database:/opt/nifi-registry/nifi-registry-current/database
      - nifi_registry_flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
      - ./flows:/opt/nifi/nifi-current/flows
    networks:
      - nifi_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18080/nifi-registry"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 2m
    labels:
      - "com.nifi.environment=staging"
      - "com.nifi.service=registry"

  nifi:
    image: apache/nifi:2.6.0
    container_name: nifi-staging
    hostname: nifi
    user: root
    ports:
      - "${NIFI_HTTPS_PORT}:8443"
    mem_limit: 4g
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=${NIFI_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_PASSWORD}
      - NIFI_WEB_HTTPS_PORT=${NIFI_HTTPS_PORT}
      - NIFI_WEB_HTTPS_HOST=${NIFI_WEB_HTTPS_HOST}
      - NIFI_WEB_PROXY_HOST=${NIFI_WEB_PROXY_HOST}
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_ELECTION_MAX_WAIT=${NIFI_ELECTION_MAX_WAIT}
      - NIFI_SENSITIVE_PROPS_KEY=${NIFI_SENSITIVE_PROPS_KEY}
      - NIFI_JVM_HEAP_INIT=2g
      - NIFI_JVM_HEAP_MAX=3g
      - JAVA_OPTS=-Djdk.tls.server.enableSNIExtension=false
      - ENVIRONMENT=staging
    command: >
      bash -c "
      cat /tmp/bootstrap-additions.conf >> /opt/nifi/nifi-current/conf/bootstrap.conf &&
      /opt/nifi/scripts/start.sh
      "
    restart: unless-stopped
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_nar_extensions:/opt/nifi/nifi-current/nar_extensions
      - nifi_python_extensions:/opt/nifi/nifi-current/python_extensions
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_logs:/opt/nifi/nifi-current/logs
      - ./flows:/opt/nifi/nifi-current/flows
      - ./config/bootstrap-additions.conf:/tmp/bootstrap-additions.conf:ro
    networks:
      - nifi_network
    depends_on:
      nifi-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8443/nifi"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    labels:
      - "com.nifi.environment=staging"
      - "com.nifi.service=nifi"