networks:
  nifi_network:
    driver: bridge

volumes:
  nifi_conf:

services:

  nifi-registry:
    image: apache/nifi-registry:2.6.0
    container_name: nifi-registry-staging
    hostname: nifi-registry
    user: root
    ports:
      - "${NIFI_REGISTRY_PORT}:18080"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=${NIFI_REGISTRY_PORT}
      - NIFI_REGISTRY_WEB_HTTP_HOST=${NIFI_REGISTRY_HOST}
      - ENVIRONMENT=staging
    mem_limit: 2g
    restart: unless-stopped
    volumes:
      - ./data/nifi_registry_database:/opt/nifi-registry/nifi-registry-current/database
      - ./data/nifi_registry_flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
      - ./flows:/opt/nifi/nifi-current/flows
    networks:
      - nifi_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18080/nifi-registry"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 2m
    labels:
      - "com.nifi.environment=staging"
      - "com.nifi.service=registry"

  nifi:
    image: apache/nifi:2.6.0
    container_name: nifi-staging
    hostname: nifi
    user: root
    ports:
      - "${NIFI_HTTPS_PORT}:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=${NIFI_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_PASSWORD}
      - NIFI_WEB_HTTPS_PORT=${NIFI_HTTPS_PORT}
      - NIFI_WEB_HTTPS_HOST=${NIFI_WEB_HTTPS_HOST}
      - NIFI_WEB_PROXY_HOST=${NIFI_WEB_PROXY_HOST}
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_ELECTION_MAX_WAIT=${NIFI_ELECTION_MAX_WAIT}
      - NIFI_SENSITIVE_PROPS_KEY=${NIFI_SENSITIVE_PROPS_KEY}
      - NIFI_JVM_HEAP_INIT=4g
      - NIFI_JVM_HEAP_MAX=4g
      - JAVA_OPTS=-Djdk.tls.server.enableSNIExtension=false
      - ENVIRONMENT=staging
      - NIFI_REGISTRY_URL=${REGISTRY_URL}
      - INITIAL_ADMIN_IDENTITY=${NIFI_USERNAME}
    command: >
      bash -c "
      # Wait for NiFi to initialize config files
      if [ ! -f /opt/nifi/nifi-current/conf/bootstrap.conf ]; then
        echo 'Waiting for NiFi to initialize configuration...'
        timeout 30 bash -c 'until [ -f /opt/nifi/nifi-current/conf/bootstrap.conf ]; do sleep 1; done' || {
          echo 'Creating initial configuration from template...'
          cp -rn /opt/nifi/nifi-current/conf.default/* /opt/nifi/nifi-current/conf/ 2>/dev/null || true
        }
      fi
      
      # Apply custom bootstrap additions if they exist
      if [ -f /tmp/bootstrap-additions.conf ] && [ -f /opt/nifi/nifi-current/conf/bootstrap.conf ]; then
        if ! grep -q 'bootstrap-additions.conf' /opt/nifi/nifi-current/conf/bootstrap.conf; then
          cat /tmp/bootstrap-additions.conf >> /opt/nifi/nifi-current/conf/bootstrap.conf
          echo 'Bootstrap additions applied'
        fi
      fi
      
      # Setup hot-reload directory
      mkdir -p /opt/nifi/nifi-current/conf/hot-reload
      
      # Create default variables.properties if not exists
      if [ ! -f /opt/nifi/nifi-current/conf/hot-reload/variables.properties ]; then
        echo '# Hot-reloadable variables' > /opt/nifi/nifi-current/conf/hot-reload/variables.properties
        echo '# NiFi will automatically reload when this file changes' >> /opt/nifi/nifi-current/conf/hot-reload/variables.properties
        echo '# Environment: staging' >> /opt/nifi/nifi-current/conf/hot-reload/variables.properties
        echo 'Hot-reload variables file created'
      fi
      
      # Configure Registry Client if not already configured
      REGISTRY_CLIENT_FILE='/opt/nifi/nifi-current/conf/registry-clients.xml'
      if [ ! -f \"\$REGISTRY_CLIENT_FILE\" ] || ! grep -q 'Staging Registry' \"\$REGISTRY_CLIENT_FILE\"; then
        echo 'Configuring NiFi Registry Client...'
        cat > \"\$REGISTRY_CLIENT_FILE\" <<'EOF'
      <?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>
      <registryClients>
          <registryClient>
              <id>staging-registry</id>
              <name>Staging Registry</name>
              <url>http://nifi-registry:18080</url>
              <description>Staging environment NiFi Registry</description>
          </registryClient>
      </registryClients>
      EOF
        echo 'Registry client configuration created'
      fi
      
      # Validate required environment variables
      if [ -z \"\$NIFI_PASSWORD\" ] || [ -z \"\$NIFI_SENSITIVE_PROPS_KEY\" ]; then
        echo 'ERROR: Required environment variables not set!'
        echo 'Please ensure NIFI_PASSWORD and NIFI_SENSITIVE_PROPS_KEY are configured in .env.staging'
        exit 1
      fi
      
      # Validate VM infrastructure variables for remote deployment
      if [ -z \"\$NIFI_WEB_PROXY_HOST\" ]; then
        echo 'WARNING: NIFI_WEB_PROXY_HOST not set. This may cause issues with remote access.'
        echo 'Ensure Terraform has populated this value in .env.staging'
      fi
      
      # Start background process to watch for config changes
      (
        while true; do
          if [ -f /opt/nifi/nifi-current/conf/hot-reload/reload-trigger ]; then
            echo '[Hot Reload] Config change detected - reloading...'
            rm /opt/nifi/nifi-current/conf/hot-reload/reload-trigger
          fi
          sleep 5
        done
      ) &
      
      echo 'Starting NiFi in staging mode...'
      echo 'JVM Heap: 4g/4g'
      echo 'Registry URL: ${REGISTRY_URL}'
      
      # Start NiFi
      /opt/nifi/scripts/start.sh
      "
    mem_limit: 6g
    restart: unl