networks:
  nifi_network:
    driver: bridge
    name: nifi_network_production

volumes:
  nifi_conf:
    name: nifi_conf_production
  nifi_database_repository:
    name: nifi_database_repository_production
  nifi_flowfile_repository:
    name: nifi_flowfile_repository_production
  nifi_content_repository:
    name: nifi_content_repository_production
  nifi_provenance_repository:
    name: nifi_provenance_repository_production
  nifi_state:
    name: nifi_state_production
  nifi_logs:
    name: nifi_logs_production

services:

  nifi-registry:
    image: apache/nifi-registry:2.6.0
    container_name: nifi-registry-production
    hostname: nifi-registry-production
    user: "1000:1000"
    env_file:
      - .env.production
    ports:
      - "${NIFI_REGISTRY_PORT}:18080"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
      - NIFI_REGISTRY_WEB_HTTP_HOST=0.0.0.0
      - ENVIRONMENT=production
      - TZ=UTC
    mem_limit: 4g
    mem_reservation: 2g
    restart: always
    volumes:
      - ./registry_data/nifi_registry_database:/opt/nifi-registry/nifi-registry-current/database
      - ./registry_data/nifi_registry_flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
      - ./flows:/opt/nifi/nifi-current/flows:ro
    networks:
      - nifi_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18080/nifi-registry"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 180s
    labels:
      - "com.nifi.environment=production"
      - "com.nifi.service=registry"
      - "com.nifi.version=2.6.0"
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
    security_opt:
      - no-new-privileges:true

  nifi:
    image: apache/nifi:2.6.0
    container_name: nifi-production
    hostname: nifi-production
    user: "1000:1000"
    env_file:
      - .env.production
    ports:
      - "${NIFI_HTTPS_PORT}:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=${NIFI_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${NIFI_PASSWORD}
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
      - NIFI_WEB_PROXY_HOST=${NIFI_WEB_PROXY_HOST}
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_SENSITIVE_PROPS_KEY=${NIFI_SENSITIVE_PROPS_KEY}
      - NIFI_JVM_HEAP_INIT=5g
      - NIFI_JVM_HEAP_MAX=5g
      - JAVA_OPTS=-Djdk.tls.server.enableSNIExtension=false -Djava.security.egd=file:/dev/urandom -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      - NIFI_REGISTRY_URL=http://nifi-registry-production:18080
      - ENVIRONMENT=production
      - TZ=UTC
    mem_limit: 8g
    mem_reservation: 5g
    restart: always
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_logs:/opt/nifi/nifi-current/logs
      - ./flows:/opt/nifi/nifi-current/flows:ro
      - ./config/bootstrap-additions.conf:/tmp/bootstrap-additions.conf:ro
    networks:
      - nifi_network
    depends_on:
      nifi-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:8443/nifi"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 300s
    labels:
      - "com.nifi.environment=production"
      - "com.nifi.service=nifi"
      - "com.nifi.version=2.6.0"
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
    security_opt:
      - no-new-privileges:true
    ulimits:
      nofile:
        soft: 50000
        hard: 50000